[package]
name = "hush_demo"
version = "0.1.0"
edition = "2021"

[lib]
name = "hush_demo"
crate-type = ["cdylib", "rlib"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
actix-web = "4"
